services:
  syslog-ng:
    image: balabit/syslog-ng:latest
    container_name: nfg-syslog-forwarder
    restart: always
    ports:
      - "514:514/udp"
      - "1025:1025/udp"
    volumes:
      - ./syslog/syslog-ng.conf:/etc/syslog-ng/syslog-ng.conf
