services:
  syslog-ng:
    image: balabit/syslog-ng:latest
    container_name: syslog-ng
    restart: always
    ports:
      - "514:514/udp"
      - "601:601"
      - "6514:6514"
    volumes:
      - ./syslog-ng.conf:/etc/syslog-ng/syslog-ng.conf
      - ./entrypoint.sh:/entrypoint.sh
    environment:
      X_API_KEY: "<your-license-key>"
      X_BLOCKLISTS: "<list-of-blocklists>"
    entrypoint: ./entrypoint.sh